<script lang="ts">

import WorkExperienceItem from './WorkExperienceItem.svelte';

</script>

<WorkExperienceItem
    jobTitle="Internship in Artificial Intelligence"
    employer="Picomto"
    start="September 2020"
    end="February 2021"
>
    <ul>
        <li>Automatic filtering of notifications generated by Picomto’s software.</li>
        <li>Anomaly detection.</li>
        <li>Automatic reading of pictures of meters.</li>
    </ul>
</WorkExperienceItem>
